import { 
  Waves, 
  Dumbbell, 
  Home, 
  SmilePlus, 
  TreePine, 
  Shield, 
  Zap, 
  Car, 
  Footprints, 
  Gamepad2,
  CheckCircle,
  Building2,
  Camera,
  Battery,
  ArrowUpDown,
  Sparkles,
  Wifi,
  Phone,
  Flame,
  Droplets,
  CloudRain,
  Sun,
  Building,
  ChefHat,
  Snowflake,
  FlameKindling,
  Heart,
  Plug,
  Bell,
  Library,
  Baby,
  CircleDot,
  type LucideIcon
} from "lucide-react";

export const amenityIcons: Record<string, LucideIcon> = {
  "swimming pool": Waves,
  "pool": Waves,
  "gym": Dumbbell,
  "gymnasium": Dumbbell,
  "fitness": Dumbbell,
  "parking": Car,
  "covered parking": Car,
  "garden": TreePine,
  "landscaped garden": TreePine,
  "landscaped gardens": TreePine,
  "clubhouse": Home,
  "club house": Home,
  "security": Shield,
  "24/7 security": Shield,
  "cctv": Camera,
  "power backup": Zap,
  "lift": ArrowUpDown,
  "elevator": ArrowUpDown,
  "children's play area": SmilePlus,
  "children play area": SmilePlus,
  "play area": SmilePlus,
  "tennis": CircleDot,
  "basketball": CircleDot,
  "badminton": CircleDot,
  "jogging track": Footprints,
  "spa": Sparkles,
  "sauna": Sparkles,
  "wifi": Wifi,
  "intercom": Phone,
  "fire safety": Flame,
  "water supply": Droplets,
  "rainwater harvesting": CloudRain,
  "solar": Sun,
  "terrace": Building,
  "balcony": Building,
  "modular kitchen": ChefHat,
  "air conditioning": Snowflake,
  "ac": Snowflake,
  "gas pipeline": FlameKindling,
  "meditation": Heart,
  "yoga": Heart,
  "amphitheatre": Building2,
  "library": Library,
  "pet friendly": Baby,
  "ev charging": Plug,
  "concierge": Bell,
  "indoor games": Gamepad2,
  "games": Gamepad2,
  "default": CheckCircle
};

export function getAmenityIcon(amenity: string): LucideIcon {
  const lowerAmenity = amenity.toLowerCase().trim();
  for (const [key, icon] of Object.entries(amenityIcons)) {
    if (lowerAmenity.includes(key)) return icon;
  }
  return amenityIcons.default;
}

// Keep the old emoji-based function for backward compatibility if needed
export const amenityIconsEmoji: Record<string, string> = {
  "swimming pool": "🏊",
  "pool": "🏊",
  "gym": "💪",
  "gymnasium": "💪",
  "fitness": "💪",
  "parking": "🅿️",
  "garden": "🌳",
  "landscaped garden": "🌳",
  "clubhouse": "🏠",
  "club house": "🏠",
  "security": "🔒",
  "24/7 security": "🔒",
  "cctv": "📹",
  "power backup": "🔋",
  "lift": "🛗",
  "elevator": "🛗",
  "children's play area": "🎢",
  "play area": "🎢",
  "tennis": "🎾",
  "basketball": "🏀",
  "badminton": "🏸",
  "jogging track": "🏃",
  "spa": "💆",
  "sauna": "🧖",
  "wifi": "📶",
  "intercom": "📞",
  "fire safety": "🧯",
  "water supply": "💧",
  "rainwater harvesting": "🌧️",
  "solar": "☀️",
  "terrace": "🏗️",
  "balcony": "🏠",
  "modular kitchen": "🍳",
  "air conditioning": "❄️",
  "ac": "❄️",
  "gas pipeline": "🔥",
  "meditation": "🧘",
  "yoga": "🧘",
  "amphitheatre": "🎭",
  "library": "📚",
  "pet friendly": "🐕",
  "ev charging": "🔌",
  "concierge": "🛎️",
  "default": "✓"
};

export function getAmenityIconEmoji(amenity: string): string {
  const lowerAmenity = amenity.toLowerCase();
  for (const [key, icon] of Object.entries(amenityIconsEmoji)) {
    if (lowerAmenity.includes(key)) return icon;
  }
  return amenityIconsEmoji.default;
}
