/**
 * Auto-generated by scripts/seo-agent/faq-generator.mjs
 * DO NOT EDIT MANUALLY — re-run the generator to update.
 *
 * Generates FAQPage JSON-LD schema for micro-market intelligence pages.
 * Import and call in your page's generateMetadata or as a JSON-LD <script> tag.
 */

export interface MicroMarketFaqInput {
  name: string;
  slug?: string | null;
  city_slug?: string | null;
  price_per_sqft_min?: number | null;
  price_per_sqft_max?: number | null;
  annual_appreciation_min?: number | null;
  hero_hook?: string | null;
  description?: string | null;
}

export interface MicroMarketProjectSummary {
  name: string;
  slug?: string | null;
  developer_name?: string | null;
  current_status?: string | null;
  price_min?: number | null;
}

/**
 * Generate FAQPage JSON-LD for a micro-market intelligence page.
 * Returns a schema.org FAQPage object ready to embed as JSON-LD.
 *
 * @param microMarket - The micro-market record
 * @param projects    - Projects in this micro-market (used for "best projects" question)
 */
export function generateMicroMarketFaq(
  microMarket: MicroMarketFaqInput,
  projects: MicroMarketProjectSummary[] = []
): Record<string, unknown> {
  const name = microMarket.name || "this area";
  const cityLabel = microMarket.city_slug
    ? microMarket.city_slug.charAt(0).toUpperCase() + microMarket.city_slug.slice(1)
    : "Hyderabad";

  // Average price answer
  let priceAnswer: string;
  if (microMarket.price_per_sqft_min && microMarket.price_per_sqft_max) {
    priceAnswer =
      "Property prices in " + name + " currently range from \u20B9" +
      microMarket.price_per_sqft_min.toLocaleString("en-IN") + " to \u20B9" +
      microMarket.price_per_sqft_max.toLocaleString("en-IN") + " per sq ft " +
      "for residential apartments. Actual pricing varies by project, floor, and unit configuration. " +
      "Contact RE/MAX Westside Realty for current market rates.";
  } else if (microMarket.price_per_sqft_min) {
    priceAnswer =
      "Average residential property prices in " + name + " start from \u20B9" +
      microMarket.price_per_sqft_min.toLocaleString("en-IN") + " per sq ft. " +
      "Contact RE/MAX Westside Realty for detailed pricing across projects.";
  } else {
    priceAnswer =
      "Contact RE/MAX Westside Realty for the current average property prices in " + name + ". " +
      "Our advisors track live pricing across all major projects in the corridor.";
  }

  // Best projects answer
  let bestProjectsAnswer: string;
  const topProjects = projects.slice(0, 5);
  if (topProjects.length > 0) {
    const projectNames = topProjects.map((p) => p.name).join(", ");
    bestProjectsAnswer =
      "Some of the top residential projects in " + name + " include: " + projectNames + ". " +
      "These projects are handpicked by RE/MAX Westside Realty advisors based on " +
      "developer credibility, RERA compliance, location, and value. " +
      "Explore all projects on our " + name + " page for detailed comparisons.";
  } else {
    bestProjectsAnswer =
      "RE/MAX Westside Realty covers multiple RERA-registered projects in " + name + ". " +
      "Browse our listings page for curated projects with advisor notes, " +
      "pricing, and possession timelines.";
  }

  // Investment answer
  let investmentAnswer: string;
  if (microMarket.annual_appreciation_min && microMarket.annual_appreciation_min > 0) {
    investmentAnswer =
      name + " has recorded annual appreciation of " + microMarket.annual_appreciation_min + "% in recent years, " +
      "making it one of " + cityLabel + "'s attractive investment corridors. " +
      (microMarket.hero_hook ? microMarket.hero_hook + " " : "") +
      "Factors like proximity to IT employment hubs, infrastructure development, and " +
      "limited supply of quality inventory support its investment thesis. " +
      "Speak with a RE/MAX Westside Realty advisor for a personalised investment assessment.";
  } else {
    investmentAnswer =
      name + " is an established residential corridor in " + cityLabel + " with " +
      (microMarket.hero_hook ? microMarket.hero_hook.toLowerCase() + " " : "strong demand drivers and ") +
      "good long-term investment potential. " +
      "Contact RE/MAX Westside Realty for an investment analysis tailored to your goals.";
  }

  // Appreciation answer
  let appreciationAnswer: string;
  if (microMarket.annual_appreciation_min && microMarket.annual_appreciation_min > 0) {
    appreciationAnswer =
      "Properties in " + name + " have appreciated at approximately " +
      microMarket.annual_appreciation_min + "% per annum " +
      "based on recent transaction data. " +
      "Appreciation is driven by improving infrastructure, employment growth in nearby IT parks, " +
      "and demand from working professionals. Past performance is indicative; " +
      "actual returns depend on specific project, floor, and holding period.";
  } else {
    appreciationAnswer =
      "Annual property appreciation in " + name + " varies by project type and location within the corridor. " +
      "RE/MAX Westside Realty advisors can share recent transaction data and appreciation trends. " +
      "Contact us for a micro-market investment report.";
  }

  // Project count answer
  const projectCount = projects.length;
  const countAnswer = projectCount > 0
    ? "There are " + projectCount + " residential projects listed in " + name + " on Westside Realty. " +
      "These include under-construction, ready-to-move, and upcoming projects by various developers. " +
      "Use our micro-market page to filter by budget, BHK type, and possession timeline."
    : "RE/MAX Westside Realty lists multiple residential projects in " + name + ". " +
      "Browse our " + name + " page to see all available options with pricing, RERA status, and advisor insights.";

  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: [
      {
        "@type": "Question",
        name: "What is the average property price in " + name + "?",
        acceptedAnswer: { "@type": "Answer", text: priceAnswer },
      },
      {
        "@type": "Question",
        name: "Which are the best projects in " + name + "?",
        acceptedAnswer: { "@type": "Answer", text: bestProjectsAnswer },
      },
      {
        "@type": "Question",
        name: "Is " + name + " a good area to invest in " + cityLabel + "?",
        acceptedAnswer: { "@type": "Answer", text: investmentAnswer },
      },
      {
        "@type": "Question",
        name: "What is the annual appreciation in " + name + "?",
        acceptedAnswer: { "@type": "Answer", text: appreciationAnswer },
      },
      {
        "@type": "Question",
        name: "How many residential projects are available in " + name + "?",
        acceptedAnswer: { "@type": "Answer", text: countAnswer },
      },
    ],
  };
}
