/**
 * Auto-generated by scripts/seo-agent/faq-generator.mjs
 * DO NOT EDIT MANUALLY — re-run the generator to update.
 *
 * Generates FAQPage JSON-LD schema for project detail pages.
 * Import and call in your page's generateMetadata or as a JSON-LD <script> tag.
 */

export interface ProjectFaqInput {
  name: string;
  price_min?: number | null;
  price_max?: number | null;
  rera_id?: string | null;
  developer_name?: string | null;
  micro_market_name?: string | null;
  city_slug?: string | null;
  current_status?: string | null;
  min_area?: number | null;
  max_area?: number | null;
  amenities_json?: string[] | string | null;
}

/** Format a rupee amount in Indian style: ₹X Cr or ₹X L */
function formatRupees(amount: number | null | undefined): string {
  if (!amount || amount <= 0) return "price on request";
  if (amount >= 10_000_000) {
    const cr = (amount / 10_000_000).toFixed(2).replace(/\.?0+$/, "");
    return "\u20B9" + cr + " Cr";
  }
  if (amount >= 100_000) {
    const l = (amount / 100_000).toFixed(2).replace(/\.?0+$/, "");
    return "\u20B9" + l + " L";
  }
  return "\u20B9" + amount.toLocaleString("en-IN");
}

/** Parse amenities from JSON string or array */
function parseAmenities(raw: string[] | string | null | undefined): string[] {
  if (!raw) return [];
  if (Array.isArray(raw)) return raw.filter(Boolean).slice(0, 5);
  try {
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) return parsed.filter(Boolean).slice(0, 5);
  } catch {
    // not JSON — ignore
  }
  return [];
}

/**
 * Generate FAQPage JSON-LD for a project detail page.
 * Returns a schema.org FAQPage object ready to embed as JSON-LD.
 */
export function generateProjectFaq(project: ProjectFaqInput): Record<string, unknown> {
  const name = project.name || "This Project";
  const cityLabel =
    project.city_slug
      ? project.city_slug.charAt(0).toUpperCase() + project.city_slug.slice(1)
      : "Hyderabad";
  const locationLabel = [project.micro_market_name, cityLabel]
    .filter(Boolean)
    .join(", ");

  // Price answer
  let priceAnswer: string;
  if (project.price_min && project.price_max && project.price_min !== project.price_max) {
    priceAnswer =
      "Prices at " + name + " range from " + formatRupees(project.price_min) + " to " +
      formatRupees(project.price_max) + ". " +
      "For the latest pricing and availability, contact RE/MAX Westside Realty.";
  } else if (project.price_min) {
    priceAnswer =
      "Prices at " + name + " start from " + formatRupees(project.price_min) + ". " +
      "Contact RE/MAX Westside Realty for current availability.";
  } else {
    priceAnswer =
      "Please contact RE/MAX Westside Realty for current pricing at " + name + ".";
  }

  // RERA answer
  const reraAnswer = project.rera_id
    ? "Yes, " + name + " is RERA registered. The RERA registration number is " + project.rera_id + ". " +
      "You can verify this on the Telangana RERA portal (TSRERA)."
    : "RERA registration details for " + name + " can be confirmed with the developer. " +
      "Contact RE/MAX Westside Realty for the latest compliance information.";

  // Developer answer
  const developerAnswer = project.developer_name
    ? name + " is developed by " + project.developer_name + ", a reputed real estate developer " +
      "operating in " + cityLabel + ". RE/MAX Westside Realty is an authorised channel partner."
    : "Please contact RE/MAX Westside Realty for developer information about " + name + ".";

  // Location answer
  const locationAnswer = locationLabel
    ? name + " is located in " + locationLabel + ". " +
      (project.micro_market_name
        ? project.micro_market_name + " is one of " + cityLabel + "'s key residential corridors, " +
          "well connected to major IT hubs and business districts."
        : "It offers good connectivity to employment centres and social infrastructure.")
    : "Please contact RE/MAX Westside Realty for location details on " + name + ".";

  // Possession/status answer
  let statusAnswer: string;
  const status = (project.current_status || "").toLowerCase();
  if (status.includes("ready") || status.includes("completed") || status.includes("possession")) {
    statusAnswer =
      name + " is " + project.current_status + " \u2014 units are available for immediate possession. " +
      "Contact RE/MAX Westside Realty to schedule a site visit.";
  } else if (status.includes("under") || status.includes("construction")) {
    statusAnswer =
      name + " is currently under construction. " +
      "For the expected possession date and construction progress, contact RE/MAX Westside Realty.";
  } else if (project.current_status) {
    statusAnswer =
      "The current status of " + name + " is: " + project.current_status + ". " +
      "Contact RE/MAX Westside Realty for the latest project updates.";
  } else {
    statusAnswer =
      "Contact RE/MAX Westside Realty for the current possession status of " + name + ".";
  }

  // Unit types answer
  let unitsAnswer: string;
  if (project.min_area && project.max_area) {
    unitsAnswer =
      name + " offers apartment configurations ranging from " + project.min_area + " sq ft to " +
      project.max_area + " sq ft. " +
      "Typical configurations include 2 BHK, 3 BHK, and premium 4 BHK options, " +
      "depending on the tower and floor. Contact us for the floor-plan brochure.";
  } else if (project.min_area) {
    unitsAnswer =
      "Units at " + name + " start from " + project.min_area + " sq ft. " +
      "Contact RE/MAX Westside Realty for detailed floor plans and available configurations.";
  } else {
    const amenities = parseAmenities(project.amenities_json);
    unitsAnswer = amenities.length
      ? name + " offers multiple apartment configurations. Key amenities include " +
        amenities.join(", ") + ". Contact RE/MAX Westside Realty for the full brochure."
      : "Contact RE/MAX Westside Realty for unit types and floor plans available at " + name + ".";
  }

  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: [
      {
        "@type": "Question",
        name: "What is the price of " + name + "?",
        acceptedAnswer: { "@type": "Answer", text: priceAnswer },
      },
      {
        "@type": "Question",
        name: "Is " + name + " RERA registered?",
        acceptedAnswer: { "@type": "Answer", text: reraAnswer },
      },
      {
        "@type": "Question",
        name: "Who is the developer of " + name + "?",
        acceptedAnswer: { "@type": "Answer", text: developerAnswer },
      },
      {
        "@type": "Question",
        name: "Where is " + name + " located?",
        acceptedAnswer: { "@type": "Answer", text: locationAnswer },
      },
      {
        "@type": "Question",
        name: "What is the possession status of " + name + "?",
        acceptedAnswer: { "@type": "Answer", text: statusAnswer },
      },
      {
        "@type": "Question",
        name: "What types of units are available in " + name + "?",
        acceptedAnswer: { "@type": "Answer", text: unitsAnswer },
      },
    ],
  };
}
