import { createServiceClient } from "@/lib/supabase/serviceClient";

export type SimulationTableName = "crm_leads" | "crm_tasks" | "crm_lead_activities" | "crm_lead_behaviour" | "crm_behavior_events";

export interface SimulationColumnMeta {
  name: string;
  dataType: string;
  nullable: boolean;
  required: boolean;
}

export interface SimulationTableSchema {
  table: SimulationTableName;
  exists: boolean;
  columns: Record<string, SimulationColumnMeta>;
  requiredColumns: string[];
}

export interface SimulationSchemaMap {
  fetchedAt: string;
  tables: Record<SimulationTableName, SimulationTableSchema>;
  behaviorTable: "crm_lead_behaviour" | "crm_behavior_events" | null;
}

const CACHE_TTL_MS = 5 * 60 * 1000;
let schemaCache: { value: SimulationSchemaMap; expiresAt: number } | null = null;

const TABLES: SimulationTableName[] = [
  "crm_leads",
  "crm_tasks",
  "crm_lead_activities",
  "crm_lead_behaviour",
  "crm_behavior_events",
];

const emptyTableSchema = (table: SimulationTableName): SimulationTableSchema => ({
  table,
  exists: false,
  columns: {},
  requiredColumns: [],
});

const buildFallbackMap = (): SimulationSchemaMap => {
  const tables = TABLES.reduce(
    (acc, table) => {
      acc[table] = emptyTableSchema(table);
      return acc;
    },
    {} as Record<SimulationTableName, SimulationTableSchema>
  );
  return {
    fetchedAt: new Date().toISOString(),
    tables,
    behaviorTable: null,
  };
};

const resolveSchemaDefinitions = (spec: Record<string, unknown>): Record<string, unknown> => {
  const components = (spec.components as Record<string, unknown> | undefined)?.schemas;
  if (components && typeof components === "object") return components as Record<string, unknown>;
  const definitions = spec.definitions;
  if (definitions && typeof definitions === "object") return definitions as Record<string, unknown>;
  return {};
};

const parseTableSchema = (table: SimulationTableName, definitions: Record<string, unknown>): SimulationTableSchema => {
  const raw = definitions[table];
  if (!raw || typeof raw !== "object") {
    return emptyTableSchema(table);
  }

  const schemaObject = raw as Record<string, unknown>;
  const properties = (schemaObject.properties as Record<string, unknown> | undefined) || {};
  const requiredSet = new Set(((schemaObject.required as string[] | undefined) || []).map((x) => String(x)));

  const columns: Record<string, SimulationColumnMeta> = {};
  const isAutoGeneratedColumn = (name: string, property: Record<string, unknown>, dataType: string): boolean => {
    const normalized = name.toLowerCase();
    if (
      normalized === "id" ||
      normalized.endsWith("_id") ||
      normalized === "created_at" ||
      normalized === "updated_at" ||
      normalized === "last_activity_at"
    ) {
      return true;
    }
    if (property.readOnly === true || property["x-readOnly"] === true) return true;
    if (property.default !== undefined || property["x-default"] !== undefined) return true;
    if (dataType.toLowerCase().includes("uuid") && normalized === "id") return true;
    return false;
  };

  for (const [name, value] of Object.entries(properties)) {
    const property = (value || {}) as Record<string, unknown>;
    const nullableFlag =
      property.nullable === true ||
      property["x-nullable"] === true ||
      (Array.isArray(property.type) && (property.type as unknown[]).includes("null"));

    const typeValue = property.type;
    const dataType = Array.isArray(typeValue)
      ? String(typeValue.filter((item) => item !== "null")[0] || "unknown")
      : String(typeValue || property.format || "unknown");

    const required = requiredSet.has(name) && !isAutoGeneratedColumn(name, property, dataType);
    columns[name] = {
      name,
      dataType,
      nullable: nullableFlag || !required,
      required,
    };
  }

  const requiredColumns = Object.values(columns)
    .filter((column) => column.required && !column.nullable)
    .map((column) => column.name);

  return {
    table,
    exists: true,
    columns,
    requiredColumns,
  };
};

export async function getSimulationSchemaMap(forceRefresh = false): Promise<SimulationSchemaMap> {
  if (!forceRefresh && schemaCache && Date.now() < schemaCache.expiresAt) {
    return schemaCache.value;
  }

  const supabase = createServiceClient();
  const resolved = buildFallbackMap();
  try {
    const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
    const serviceRoleKey =
      process.env.SUPABASE_SERVICE_ROLE_KEY ||
      process.env.SUPABASE_SERVICE_ROLE ||
      process.env.SUPABASE_SERVICE_KEY;

    if (!url || !serviceRoleKey) {
      throw new Error("Missing Supabase environment for schema discovery.");
    }

    // Keep a tiny call via Supabase client so schema discovery remains tied to Supabase service availability.
    await supabase.from("crm_users").select("id").limit(1);

    const response = await fetch(`${url}/rest/v1/`, {
      method: "GET",
      headers: {
        apikey: serviceRoleKey,
        Authorization: `Bearer ${serviceRoleKey}`,
        Accept: "application/openapi+json",
      },
      cache: "no-store",
    });

    if (!response.ok) {
      throw new Error(`Schema discovery failed with status ${response.status}.`);
    }

    const spec = (await response.json()) as Record<string, unknown>;
    const definitions = resolveSchemaDefinitions(spec);
    for (const table of TABLES) {
      resolved.tables[table] = parseTableSchema(table, definitions);
    }
    resolved.fetchedAt = new Date().toISOString();
    resolved.behaviorTable = resolved.tables.crm_lead_behaviour.exists
      ? "crm_lead_behaviour"
      : resolved.tables.crm_behavior_events.exists
        ? "crm_behavior_events"
        : null;
  } catch {
    // Use fallback empty schema map. Simulation engine will log clear missing-table errors.
  }

  schemaCache = {
    value: resolved,
    expiresAt: Date.now() + CACHE_TTL_MS,
  };
  return resolved;
}

export function sanitizePayloadForTable(
  tableSchema: SimulationTableSchema,
  payload: Record<string, unknown>
): {
  payload: Record<string, unknown>;
  missingRequiredFields: string[];
  droppedFields: string[];
} {
  const sanitized: Record<string, unknown> = {};
  const dropped: string[] = [];

  const coerce = (value: unknown, dataType: string): unknown => {
    if (value === null || value === undefined) return value;
    const normalizedType = dataType.toLowerCase();
    if (normalizedType.includes("bool")) return Boolean(value);
    if (normalizedType.includes("int")) return typeof value === "number" ? Math.trunc(value) : Number(value);
    if (normalizedType.includes("numeric") || normalizedType.includes("float") || normalizedType.includes("double")) {
      return typeof value === "number" ? value : Number(value);
    }
    if (normalizedType.includes("json")) return typeof value === "object" ? value : { value };
    if (normalizedType.includes("timestamp") || normalizedType.includes("date") || normalizedType.includes("time")) {
      if (typeof value === "string") return value;
      if (value instanceof Date) return value.toISOString();
      return new Date(String(value)).toISOString();
    }
    return value;
  };

  for (const [key, value] of Object.entries(payload)) {
    const column = tableSchema.columns[key];
    if (!column) {
      dropped.push(key);
      continue;
    }
    sanitized[key] = coerce(value, column.dataType);
  }

  const missingRequiredFields = tableSchema.requiredColumns.filter((column) => {
    const value = sanitized[column];
    return value === undefined || value === null || value === "";
  });

  return {
    payload: sanitized,
    missingRequiredFields,
    droppedFields: dropped,
  };
}
